import React from 'react';
import { methodLabel, format as formatMoney } from '../../lib/money';

/**
 * The printed receipt.
 *
 * This is the only artefact in the workspace that leaves the building. The
 * patient walks out with it, and it may be the only record they ever hold of
 * what they paid — so it states what was actually tendered, in the currency it
 * was tendered in, and separately what that was worth against the invoice at
 * the rate used at that moment. A receipt that prints only the converted
 * figure is telling the patient they handed over something they did not.
 *
 * Rendered off-screen at all times and revealed only while printing, so the
 * markup that goes to the printer is the markup that was reviewed — not a
 * screen layout with the navigation hidden and its columns collapsed by a
 * media query. Everything else about the workspace is deliberately absent:
 * nobody needs the sidebar on a slip of paper.
 *
 * Two copies print on one sheet. Zimbabwean practices keep a signed office
 * copy against the day book, and reprinting the same receipt separately
 * invites the two copies to disagree.
 */

const line = (label, value) => ({ label, value });

function Copy({ receipt, practice, copyLabel }) {
  const applied = receipt.appliedToInvoice;
  const converted = Boolean(applied.rateUsed);
  const allocations = receipt.allocations ?? [];

  const details = [
    line('Receipt no.', receipt.number ?? 'Not recorded'),
    line('Date', new Date(receipt.receivedAt).toLocaleString('en-GB', { dateStyle: 'long', timeStyle: 'short' })),
    line('Patient', receipt.patient),
    line(allocations.length > 1 ? 'Invoices' : 'Invoice', receipt.invoiceReference),
    line('Method', methodLabel(receipt.method)),
    line('Received by', receipt.receivedBy),
  ];

  return (
    <article className="lh-receipt-copy">
      <header className="lh-receipt-head">
        <div>
          <p className="lh-receipt-practice">{practice.name}</p>
          <p className="lh-receipt-meta">{practice.addressLine}</p>
          <p className="lh-receipt-meta">{practice.city}</p>
          <p className="lh-receipt-meta">{practice.phone} · {practice.email}</p>
        </div>
        <div className="lh-receipt-stamp">
          <p className="lh-receipt-title">Receipt</p>
          <p className="lh-receipt-copy-label">{copyLabel}</p>
          {/* A reprint of a receipt whose original number was never recorded
              must not pass itself off as the original. */}
          {receipt.reissued && <p className="lh-receipt-copy-label">Reissued from the ledger</p>}
        </div>
      </header>

      <dl className="lh-receipt-details">
        {details.map((row) => (
          <div key={row.label} className="lh-receipt-row">
            <dt>{row.label}</dt>
            <dd>{row.value}</dd>
          </div>
        ))}
      </dl>

      {/* What the patient actually handed over. Printed largest, because it is
          the one figure they will check against the notes in their hand. */}
      <div className="lh-receipt-amount">
        <span>Received</span>
        <strong>{formatMoney(receipt.tendered.amount, receipt.tendered.currency)}</strong>
      </div>

      {converted && (
        <p className="lh-receipt-note">
          Applied as {formatMoney(applied.amount, applied.currency)} at {applied.rateUsed}.
          Rate recorded at the moment of payment.
        </p>
      )}

      {/* A tender split across an account has to name every invoice it cleared.
          "ZWL 1,700 received" against three invoices is not reconcilable. */}
      {allocations.length > 1 && (
        <table className="lh-receipt-table">
          <thead>
            <tr>
              <th>Applied to</th>
              <th>Amount</th>
              <th>Balance left</th>
            </tr>
          </thead>
          <tbody>
            {allocations.map((allocation) => (
              <tr key={allocation.invoiceId}>
                <td>{allocation.invoiceId}</td>
                <td>{formatMoney(allocation.amount, applied.currency)}</td>
                <td>{allocation.remaining > 0 ? formatMoney(allocation.remaining, applied.currency) : 'Settled'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <div className="lh-receipt-balance">
        {receipt.balanceRemaining > 0
          ? <>Balance remaining: <strong>{formatMoney(receipt.balanceRemaining, applied.currency)}</strong></>
          : <strong>Settled in full</strong>}
      </div>

      <footer className="lh-receipt-foot">
        <div className="lh-receipt-sign">
          <span />
          <p>Signature</p>
        </div>
        <p className="lh-receipt-small">
          Computer generated by Luminary Health. Retain this receipt as proof of payment.
        </p>
      </footer>
    </article>
  );
}

export function ReceiptDocument({ receipt, practice }) {
  if (!receipt) return null;
  return (
    <div className="lh-print-doc" aria-hidden="true">
      <Copy receipt={receipt} practice={practice} copyLabel="Patient copy" />
      <Copy receipt={receipt} practice={practice} copyLabel="Office copy" />
    </div>
  );
}

export default ReceiptDocument;
